### ISSUE TITLE
Not responsible section

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-boiler-readme#1]

**Comment by Thiousi** [comment]
I like that idea... Something like that maybe?

This plugin is provided as-is with no guarantee. Use it at your own risk and always test it yourself before using it in a production environment. If you find any issues, please [create a new issue](https://github.com/jenstornell/kirby-boiler-readme/issues/new).

**Comment by jenstornell** [comment]
Great! What is good for a headline? Warranty or Terms of use or something else?

**Comment by Thiousi** [comment]
I believe "Disclaimer" is quite a standard headline.

**Comment by jenstornell** [comment]
Implemented!
